### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [IZSVenezie/VetEpiGIS-Stat#1]
In particular the difference with:
http://plugins.qgis.org/plugins/VetEpiGIS-Tool/
Thanks.

**Comment by solymosin** [comment]
Dear Paolo Cavallini,

We modified the description of the plugin on github and in the
metadata.txt. It differs from the VetEpiGIS-Tool, because the Stat plugin
is not an outbreak managment tool, but a method collection for spatial
veterinary epidemiological analyses. Since the stat plugin is experimental
the functionality is not complete, this is why the implemented methods are
not detailed.

Please let me know if you would need something else to be described.

Best regards,

Norbert Solymosi DVM, PhD
associate professor
Department of Animal Hygiene, Herd-health and Veterinary Ethology
Faculty of Veterinary Science
Szent István University
H-1078 Budapest, István u. 2.
Mobil: +36-30-9-347-069

2016-06-07 9:24 GMT+02:00 Paolo Cavallini notifications@github.com:

**Comment by pcav** [comment]
Thanks. Please upload a new version then.
